### ISSUE TITLE
Update demo app for checkboxes component

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ods-flutter#142]
Update Checkbox screen to display CheckBoxListTitle and add comment "Use checkBoxListTitle or Checkbox" as in material 3 demo app:
https://flutter.github.io/samples/web/material_3_demo/#/

**Comment by B3nz01d** [comment]
@mccart77 In the demo app from M3, a checkbox has 3 states:
* unselected
* selected
* minus
do we need to allow this?

**Comment by B3nz01d** [comment]
I have added this issue as disabled interaction correction: #192
