### ISSUE TITLE
Switch Component Updates

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-flutter#191]
The current Switch page presents 2 switch types.

Questions for @mccart77 :
* should we keep the 2 options (with or without the checkmark/cross)?
* if we keep both they should be proposed as 2 component variants?

**Comment by Tayebsed93** [comment]
in the code utilise a property icon to define the 2 methods. We recommended to use a customization with a single variant

**Comment by B3nz01d** [comment]
Design has been validated on the figma file. It is ready to dev.

**Comment by B3nz01d** [comment]
for RTL support how should this be handled?
