### ISSUE TITLE
[Bug]: Snackbar without action text positioning

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-flutter#198]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-flutter/issues) for duplicate or closed feature requests

### Your test device

Any

### OS Version

Any

### App version

v1.0.0(132)

### Describe the issue

in the current version when the Snackbar, when it is used without the action button, the text positioning does not take the full width.

<img src="https://github.com/Orange-OpenSource/ods-flutter/assets/62606284/d7f97782-0c13-46d2-9f4a-bb331293c9a9" width="300">

### Expected Behavior

the text should be using the full width of the screen

**Comment by Tayebsed93** [comment]
à vérifier sur la version en android

**Comment by B3nz01d** [comment]
@Tayebsed93 this is not working in app v0.8.0 b368
