### ISSUE TITLE
[Bug]: button padding update

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-flutter#247]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-flutter/issues) for duplicate or closed feature requests

### Your test device

any

### OS Version

any

### App version

0.3 - 200

### Describe the issue

the padding (horizontalspace between the text and the border of the button) is to important

### Expected Behavior

the horizontal padding between the button text and the button border should be: spacing.s (8)

**Comment by mccart77** [comment]
![image](https://github.com/Orange-OpenSource/ods-flutter/assets/89084974/8eb301a7-b950-4a5b-8fd5-8c6f5316ecef)
