### ISSUE TITLE
[Bug]: Guideline Spacing value

### ISSUE THREAD

**Issue by mccart77** [Orange-OpenSource/ods-flutter#252]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-flutter/issues) for duplicate or closed feature requests

### Your test device

iPhone 13

### OS Version

16.1.1

### App version

0.3.0 - 200

### Describe the issue

In the Spacing page the first token 'spacingNone' has a value of '1 px'

### Expected Behavior

spacingNone should have a value of 0 px

**Comment by B3nz01d** [comment]
This has not been updated in version 0.3.0 (b212)

**Comment by Tayebsed93** [comment]
@B3nz01d sorry this is a mistake on my part. I will redo a version for tomorrow (01/11)
