### ISSUE TITLE
Update components to show label content examples

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-flutter#295]
The following component show no text next to the component and therefore does not allow to see it's normal usage:
* Radio Buttons
* Checkboxes
* Switches

As in android show examples of usage with the food json in order to understand:
* that a radio button is only allowing to use only one item at a time
* that the checkbox allows to select more then one
* that a switch is used on the same line but with the text on one side and the switch on the other

**Comment by B3nz01d** [comment]
@Tayebsed93 you can check accessibility

**Comment by Tayebsed93** [comment]
ok accessibility @B3nz01d
