### ISSUE TITLE
[Bug]: Card buttons

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-flutter#329]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-flutter/issues) for duplicate or closed feature requests

### Your test device

any

### OS Version

any

### App version

v0.8.0 b362

### Describe the issue

the buttons are using the high emphasis style

### Expected Behavior

the buttons in the cards should be using the lowest primary style

**Comment by Tayebsed93** [comment]
By default, do not include buttons for all cards
