### ISSUE TITLE
[Bug]: Icons Button name

### ISSUE THREAD

**Issue by Tayebsed93** [Orange-OpenSource/ods-flutter#334]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-flutter/issues) for duplicate or closed feature requests

### Your test device

iPhone 14 pro Max

### OS Version

iOS 17.0

### App version

v0.8.0

### Describe the issue

The name is "Buttons Icons."

### Expected Behavior

1. The name should be "Icons Button."
2. Change the order and put Segmented Button last

**Comment by B3nz01d** [comment]
@Tayebsed93 the information was to be changed base on our last discussions to "Icon Buttons"
